### ISSUE TITLE
Laravel 5.8

### ISSUE THREAD

**Issue by hotrush** [lazychaser/laravel-nestedset#356]
Any chance to upgrade dependencies?

**Comment by vahiiiid** [comment]
can't use in laravel 5.8
seems just changing "require" part of composer.json can solve it??

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install kalnoy/nestedset v4.3.3
    - Conclusion: don't install kalnoy/nestedset v4.3.2
    - Conclusion: don't install kalnoy/nestedset v4.3.1
    - Conclusion: don't install kalnoy/nestedset v4.3.0
    - Conclusion: remove laravel/framework v5.8.0
    - Installation request for kalnoy/nestedset ^4.3 -> satisfiable by kalnoy/nestedset[v4.3.0, v4.3.1, v4.3.2, v4.3.3, v4.x-dev].
    - Conclusion: don't install laravel/framework v5.8.0
    - kalnoy/nestedset v4.x-dev requires illuminate/events 5.2 - 5.7 -> satisfiable by illuminate/events[5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].

**Comment by regiszanandrea** [comment]
Please @lazychaser, add support for Laravel 5.8 😄

**Comment by lazychaser** [comment]
Done

**Comment by BenQoder** [comment]
I am still unable to install on laravel 5.8 
`composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.8.2
    - Conclusion: don't install laravel/framework v5.8.2
    - Installation request for kalnoy/nestedset ^4.3.4 -> satisfiable by kalnoy/nestedset[v4.x-dev].
    - Conclusion: don't install laravel/framework v5.8.1
    - Conclusion: don't install laravel/framework v5.8.0
    - kalnoy/nestedset v4.x-dev requires illuminate/database 5.2 - 5.7 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev], illuminate/database[5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - Can only install one of: laravel/framework[5.8.x-dev, 5.5.x-dev].
    - Can only install one of: laravel/framework[5.8.x-dev, 5.6.x-dev].
    - Can only install one of: laravel/framework[5.8.x-dev, 5.7.x-dev].
    - don't install illuminate/database 5.7.17|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database 5.7.18|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database 5.7.19|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database 5.7.x-dev|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.0|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.1|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.10|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.11|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.15|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.2|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.20|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.21|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.22|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.23|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.26|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.27|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.28|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.3|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.4|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.5|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.6|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.7|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.8|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.7.9|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database 5.4.x-dev|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.4.0|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.4.13|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.4.17|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.4.19|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.4.27|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.4.36|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.4.9|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database 5.5.x-dev|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.0|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.16|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.17|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.2|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.28|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.33|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.34|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.35|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.36|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.37|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.39|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.40|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.41|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.43|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.5.44|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database 5.6.x-dev|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.0|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.1|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.10|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.11|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.12|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.13|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.14|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.15|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.16|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.17|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.19|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.2|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.20|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.21|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.22|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.23|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.24|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.25|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.26|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.27|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.28|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.29|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.3|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.30|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.31|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.32|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.33|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.34|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.35|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.36|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.37|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.38|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.39|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.4|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.5|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.6|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.7|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.8|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.6.9|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database 5.2.x-dev|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database 5.3.x-dev|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.0|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.19|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.21|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.24|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.25|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.26|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.27|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.28|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.31|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.32|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.37|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.43|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.45|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.6|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.2.7|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.3.0|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.3.16|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.3.23|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/database v5.3.4|don't install laravel/framework 5.8.x-dev
    - Installation request for laravel/framework 5.8.* -> satisfiable by laravel/framework[5.8.x-dev, v5.8.0, v5.8.1, v5.8.2].`

**Comment by regiszanandrea** [comment]
@BenQoder Give Composer a few minutes to update it and should be good

**Comment by BenQoder** [comment]
Alright. Thanks @regiszanandrea

**Comment by BenQoder** [comment]
Should It Take This Much Time?

i also did

``
composer require kalnoy/nestedset:4.3.4
``

but got

``
  [InvalidArgumentException]
  Could not find package kalnoy/nestedset in a version matching 4.3.4
``

**Comment by regiszanandrea** [comment]
@BenQoder No take much time. I getting error on illuminate/events. @lazychaser Can help on this?

**Comment by BenQoder** [comment]
I don't think, this has been updated on https://packagist.org/packages/kalnoy/nestedset.
because v4.3.4 doesn't show yet

**Comment by lazychaser** [comment]
Updated the package, should work now

**Comment by BenQoder** [comment]
Thanks a lot
