### ISSUE TITLE
up() / down() affects nothing.

### ISSUE THREAD

**Issue by domesticlion** [lazychaser/laravel-nestedset#81]
I'm using L5.2 on PHP7.

There are 4 nodes(categories) on the root level.

```
$category = Category::find($id); // finding 2nd node.
$category->down();
```

$category->down() returns true, but all rows on category table doesn't change at all.

**Comment by lazychaser** [comment]
How do you know that the node is second? Did you apply `defaultOrder()`? Node movement is only meaningful when you apply default node order (which is not by default).

**Comment by domesticlion** [comment]
According to the value of _lft, the node I would move is the second one.

Before
id, _lft, _rgt
1, 1, 2
2, 3, 4 <<< down() // return true
3, 5, 6
4, 7, 8

After
1, 1, 2
2, 3, 4
3, 5, 6
4, 7, 8

---------------

To-Be
1, 1, 2
3, 3, 4
2, 5, 6
4, 7, 8

**Comment by lazychaser** [comment]
That's a bug. Fixed in `4.1.0@dev`.

**Comment by domesticlion** [comment]
Thank you for fixing but I still have a same problem.
And I found that this problem is caused with [dimsav/laravel-translatable](https://github.com/dimsav/laravel-translatable). Is it impossible to use these packages togather ?

**Comment by domesticlion** [comment]
I suppose this may be the problem of translatable package, because this seems to be caused by save function overridden by translatable. How do you think?
If so, I'll close this issue and discuss on the board of translatable.

**Comment by lazychaser** [comment]
Sorry, now should work fine

**Comment by lazychaser** [comment]
Ah, my fix doesn't fix. Please show me the output of this:

```php
Category::find(2)->getNextSibling();
```

**Comment by domesticlion** [comment]
OK, that is like below. (Exact my model name is ItemCategoryGroup).

```
App\ItemCategoryGroup Object
(
    [translatedAttributes] => Array
        (
            [0] => name
        )

    [guarded:protected] => Array
        (
            [0] => id
        )

    [pending:protected] => 
    [moved:protected] => 
    [connection:protected] => 
    [table:protected] => 
    [primaryKey:protected] => id
    [perPage:protected] => 15
    [incrementing] => 1
    [timestamps] => 1
    [attributes:protected] => Array
        (
            [id] => 3
            [admin_id] => 0
            [_lft] => 5
            [_rgt] => 6
            [parent_id] => 
            [key] => color
            [position] => 0
            [deleted_at] => 
            [created_at] => 2016-02-21 04:02:04
            [updated_at] => 2016-02-21 04:02:04
        )

    [original:protected] => Array
        (
            [id] => 3
            [admin_id] => 0
            [_lft] => 5
            [_rgt] => 6
            [parent_id] => 
            [key] => color
            [position] => 0
            [deleted_at] => 
            [created_at] => 2016-02-21 04:02:04
            [updated_at] => 2016-02-21 04:02:04
        )

    [relations:protected] => Array
        (
        )

    [hidden:protected] => Array
        (
        )

    [visible:protected] => Array
        (
        )

    [appends:protected] => Array
        (
        )

    [fillable:protected] => Array
        (
        )

    [dates:protected] => Array
        (
        )

    [dateFormat:protected] => 
    [casts:protected] => Array
        (
        )

    [touches:protected] => Array
        (
        )

    [observables:protected] => Array
        (
        )

    [with:protected] => Array
        (
        )

    [morphClass:protected] => 
    [exists] => 1
    [wasRecentlyCreated] => 
)
```

**Comment by lazychaser** [comment]
After looking through translatable package I realized that this is the reason of the issue. After composer update it should work fine now. But anyways, this package should reconsider the way they are saving translations and use events rather than changing `save` method.

**Comment by domesticlion** [comment]
It worked fine! I agree that the translatable package shouldn't change saving method.
Anyway, thank you for fixing and providing this awesome package!

**Comment by lazychaser** [comment]
Great, have a nice day! =)
